_wandb:
    value:
        cli_version: 0.20.2rc20250616
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
            "2":
                - 1
            "4": 3.12.0
            "5": 0.20.2rc20250616
            "8":
                - 3
            "12": 0.20.2rc20250616
            "13": windows-amd64
